### ISSUE TITLE
why is /usr/local hardcoded?

### ISSUE THREAD

**Issue by avsm** [yallop/ocaml-ctypes-build#1]
```
    flag ["c"; "compile"] & S[A"-ccopt"; A"-I/usr/local/include"];
    flag ["c"; "ocamlmklib"] & A"-L/usr/local/lib";
    flag ["ocaml"; "link"; "native"; "program"] &
      S[A"-cclib"; A"-L/usr/local/lib"];
```

Is this `/usr/local` there for something specific? Might be better to pass through a `CFLAGS` environment variable, as it is not portable behaviour to depend on something existing in `/usr/local`

**Comment by yallop** [comment]
Good point.  I'll remove the `/usr/local` references.  I'll leave `CFLAGS` out for now; it can be handled in client code easily enough.  See #2.

**Comment by avsm** [comment]
Thanks. It would be useful to have a 'standard' way of passing through client-specified flags for C compilation, both for portability and future cross-compilation.  I'll create a separate PR for that when it comes up (probably in the context of OpenBSD compilation)

**Comment by yallop** [comment]
Thanks; please do!  The current state of the package is intended as a starting point, based on rules extracted from existing projects.  Improvements for portability etc. are very welcome.
